name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --add-data "file/dictionary.txt;file" main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dir-blast-exe
          path: dist/main.exe

      - name: Get the current release version
        id: get_version
        uses: actions/github-script@v4
        with:
          script: |
            const latestRelease = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const version = latestRelease.data.tag_name;
            core.setOutput('version', version);

      - name: Bump version
        id: bump_version
        run: |
          echo "Current version: ${{ steps.get_version.outputs.version }}"
          NEW_VERSION=$(echo ${{ steps.get_version.outputs.version }} | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ env.new_version }}
          release_name: Release ${{ env.new_version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/main.exe
          asset_name: dir-blast.exe
          asset_content_type: application/octet-stream