name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyinstaller bs4 tqdm

      - name: Build executable
        run: |
          pyinstaller --onefile  --add-data "file/*;file"  main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dir-blast-exe
          path: dist/main.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v1.2.0  # 手动指定版本号
          release_name: Release v1.2.0  # 手动指定版本号
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/main.exe
          asset_name: dir-blast.exe
          asset_content_type: application/octet-stream
